force-app/main/default/objects/Org_Setting__mdt/fields/Bcc_Sender__c.field-meta.xml
<CustomField>
    <fullName>Bcc_Sender__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bcc Sender</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Org_Setting__mdt/fields/Html_Body__c.field-meta.xml
<CustomField>
    <fullName>Html_Body__c</fullName>
    <label>Html Body</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Setting__mdt/fields/Plain_Text_Body__c.field-meta.xml
<CustomField>
    <fullName>Plain_Text_Body__c</fullName>
    <label>Plain Text Body</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Setting__mdt/fields/Reply_To__c.field-meta.xml
<CustomField>
    <fullName>Reply_To__c</fullName>
    <label>Reply To</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Setting__mdt/fields/Sender_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Display_Name__c</fullName>
    <label>Sender Display Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Setting__mdt/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Setting__mdt/fields/To_Address__c.field-meta.xml
<CustomField>
    <fullName>To_Address__c</fullName>
    <defaultValue></defaultValue>
    <label>To Address</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Setting__mdt/fields/Use_Signature__c.field-meta.xml
<CustomField>
    <fullName>Use_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Signature</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SoilAnalysis__c/SoilAnalysis__c.object-meta.xml
<CustomObject>
    <label>SoilAnalysis</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>SoilAnalysis Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SoilAnalysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SoilAnalysisTriggerHelper.cls
public without sharing class SoilAnalysisTriggerHelper {
    public static Boolean sendConfirmationEmailToUser(SoilAnalysis__c sa) {
        if (Org_Setting__mdt.getInstance('SA_Email_Params')?.Is_Active__c == true) {
            Messaging.reserveSingleEmailCapacity(2);
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] { Org_Setting__mdt.getInstance('SA_Email_Params')?.To_Address__c }; 
            mail.setToAddresses(toAddresses);
            mail.setReplyTo(Org_Setting__mdt.getInstance('SA_Email_Params')?.Reply_To__c);
            mail.setSenderDisplayName(Org_Setting__mdt.getInstance('SA_Email_Params')?.Sender_Display_Name__c);
            mail.setSubject(Org_Setting__mdt.getInstance('SA_Email_Params')?.Subject__c);
            mail.setBccSender(Org_Setting__mdt.getInstance('SA_Email_Params')?.Bcc_Sender__c);
            mail.setUseSignature(Org_Setting__mdt.getInstance('SA_Email_Params')?.Use_Signature__c);
            mail.setPlainTextBody(Org_Setting__mdt.getInstance('SA_Email_Params')?.Plain_Text_Body__c);
            mail.setHtmlBody(Org_Setting__mdt.getInstance('SA_Email_Params')?.Html_Body__c);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            return true;
        } else {
            return false;
        }
        
    }
}
// 'The following Soil Analysis:<b> ' + case.Id +' </b>has been created.<p>'+
//                 'To view your case <a href=https://pisces-ocean-3469-dev-ed.scratch.lightning.force.com/'+sa.Id+'>click here.</a>'