force-app/main/default/objects/Org_Setting__mdt/fields/Reply_To__c.field-meta.xml
<CustomField>
    <fullName>Reply_To__c</fullName>
    <label>Reply To</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Setting__mdt/fields/Sender_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Display_Name__c</fullName>
    <label>Sender Display Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SoilAnalysisController.cls
public with sharing class SoilAnalysisController {
    @AuraEnabled(cacheable=true)
    public static SAEmailParams getSAEmailParams(){
        try {
            return new SAEmailParams(Org_Setting__mdt.getInstance('SA_Email_Params'));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class SAEmailParams {
        @AuraEnabled public Boolean isActive { get; set; }
        @AuraEnabled public String replyTo { get; set; }
        @AuraEnabled public String senderDisplayName { get; set; }
        
        public SAEmailParams(Org_Setting__mdt saEmailParams) {
            this.isActive = saEmailParams.Is_Active__c;
            this.replyTo = saEmailParams.Reply_To__c;
            this.senderDisplayName = saEmailParams.Sender_Display_Name__c;
        }
    }
}